### ISSUE TITLE
Can't host (JsGoogleMapsApi & GeoTIFF errors on both safari and chrome)

### ISSUE THREAD

**Issue by Kupinaaa** [ercjbnt/wreckmap#1]
I'd love to play around with it, hosted on my own machine, but I sadly can't get it to work. I keep getting google map api and GeoTIFF errors, no matter the browser (chrome / safari), and no matter whether I host it through "go live" in vs code, or just open the html file. The errors I get are provided in the screenshot and in the text below.

<img width="1470" alt="Screenshot 2024-09-29 at 8 50 31 PM" src="https://github.com/user-attachments/assets/bc9f862c-2b1c-490e-ab8c-8e3fbd80c7c8">

```
[Error] Google Maps JavaScript API error: InvalidKeyMapError
https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error
	(anonymous function) (js:175:419)
	pxa (map.js:41:355)
	kxa (map.js:40:110)
	(anonymous function) (map.js:37:175)
[Error] Error loading GeoTIFF:
RangeError: Maximum call stack size exceeded.
(anonymous function) — index.html:58
	(anonymous function) (index.html:61)
> Selected Element
< <div class="gm-err-content">…</div>
[Error] Failed to load resource: the server responded with a status of 404 () (geotiff.js.map, line 0)

```

**Comment by ercjbnt** [comment]
Haha thanks for the early user testing. Right now it's using static HTML, so you'll need to substitute your Google API key into the URL on line 175. The GeoTIFF call stack size issue is known but not critical.
